package com.evcharging.identity.domain.model;

import java.time.Instant;
import java.util.UUID;

/**
 * Domain aggregate root for a vendor user Invitation.
 *
 * <p>Pure Java — no Spring or JPA annotations.
 */
public class Invitation {

  private final UUID id;
  private final String email;
  private final UUID vendorId;
  private final Role role;
  private final String token;
  private final Instant expiresAt;
  private InvitationStatus status;
  private final Instant createdAt;

  private Invitation(
      UUID id,
      String email,
      UUID vendorId,
      Role role,
      String token,
      Instant expiresAt,
      InvitationStatus status,
      Instant createdAt) {
    this.id = id;
    this.email = email;
    this.vendorId = vendorId;
    this.role = role;
    this.token = token;
    this.expiresAt = expiresAt;
    this.status = status;
    this.createdAt = createdAt;
  }

  /**
   * Create a new invitation.
   *
   * @param email the email address to invite
   * @param vendorId the vendor this invitation belongs to
   * @param role must be VENDOR_ADMIN or VENDOR_USER
   * @param token secure random token (generated by caller)
   * @param expiresAt when the token expires
   */
  public static Invitation create(
      String email, UUID vendorId, Role role, String token, Instant expiresAt) {
    if (role != Role.VENDOR_ADMIN && role != Role.VENDOR_USER) {
      throw new IllegalArgumentException("Invitations can only be for VENDOR_ADMIN or VENDOR_USER");
    }
    return new Invitation(
        UUID.randomUUID(),
        email.toLowerCase(),
        vendorId,
        role,
        token,
        expiresAt,
        InvitationStatus.PENDING,
        Instant.now());
  }

  /**
   * Reconstitute an Invitation from persistence.
   *
   * <p>For use by infrastructure adapters only.
   */
  public static Invitation reconstitute(
      UUID id,
      String email,
      UUID vendorId,
      Role role,
      String token,
      Instant expiresAt,
      InvitationStatus status,
      Instant createdAt) {
    return new Invitation(id, email, vendorId, role, token, expiresAt, status, createdAt);
  }

  /**
   * Accept this invitation. Validates that it is still pending and not expired.
   *
   * @throws IllegalStateException if the invitation is not in PENDING status or is expired
   */
  public void accept() {
    if (this.status != InvitationStatus.PENDING) {
      throw new IllegalStateException("Invitation is not pending (status=" + status + ")");
    }
    if (Instant.now().isAfter(this.expiresAt)) {
      this.status = InvitationStatus.EXPIRED;
      throw new IllegalStateException("Invitation token has expired");
    }
    this.status = InvitationStatus.ACCEPTED;
  }

  /** Returns true if the invitation is still pending and not past its expiry time. */
  public boolean isValid() {
    return status == InvitationStatus.PENDING && Instant.now().isBefore(expiresAt);
  }

  public UUID getId() {
    return id;
  }

  public String getEmail() {
    return email;
  }

  public UUID getVendorId() {
    return vendorId;
  }

  public Role getRole() {
    return role;
  }

  public String getToken() {
    return token;
  }

  public Instant getExpiresAt() {
    return expiresAt;
  }

  public InvitationStatus getStatus() {
    return status;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }
}
